# Generated by Django 5.1 on 2025-02-19 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_item_order_report_sale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='order',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='report',
            name='tenant',
        ),
        migrations.DeleteModel(
            name='Tenant',
        ),
    ]
