# Generated by Django 5.1 on 2025-02-22 13:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('laptop', 'Laptop'), ('monitor', 'Monitor'), ('phone', 'Phone'), ('accessory', 'Accessory')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='LaptopPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_purchase', models.DateField()),
                ('warranty_period', models.IntegerField(help_text='In months')),
                ('sold_to_name', models.CharField(max_length=100)),
                ('sold_to_number', models.CharField(max_length=20)),
                ('sold_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('laptop', models.ForeignKey(limit_choices_to={'item_type': 'laptop'}, on_delete=django.db.models.deletion.CASCADE, to='purchases.warehouseitem')),
            ],
        ),
    ]
